
server:
  port: 5001

spring:
  application:
    name: GestionDeStage-Backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: "file:./uploads/"
        
        
             

  datasource:
    url: jdbc:mysql://localhost:3306/projettutore_gestiondestage
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  main:
    allow-circular-references: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE